#!/usr/bin/env python3
"""
Check consistency between `agents/`, `skills/` and generated summaries.

Produces `reports/consistency_report.md` listing:
- agent files missing from `summaries/agent_en.md` (no change block referencing the path)
- agent summary entries referencing non-existent agent files
- skill SKILL.md files missing from `summaries/skill_en.md` table
- skill summary table rows referencing non-existent SKILL.md

Run from repo root:
  python scripts/check_summaries_consistency.py
"""
import glob
import os
import re
from pathlib import Path


ROOT = Path.cwd()


def find_agent_files():
    return sorted([str(p).replace('\\\\','/') for p in ROOT.glob('agents/**/*.agent.md')])


def parse_agent_summary_paths(md_path):
    text = Path(md_path).read_text(encoding='utf-8') if md_path.exists() else ''
    paths = set()
    for m in re.finditer(r"—\s*(?P<path>[\w\-\./]+)\s*\(", text):
        p = m.group('path')
        if p.startswith('agents/'):
            paths.add(str((ROOT / p)).replace('\\\\','/'))
    return sorted(paths)


def find_skill_files():
    return sorted([str(p).replace('\\\\','/') for p in ROOT.glob('skills/**/SKILL.md')])


def parse_skill_table_sources(md_path):
    if not md_path.exists():
        return []
    lines = md_path.read_text(encoding='utf-8').splitlines()
    sources = set()
    # find table header
    for i, line in enumerate(lines):
        if line.strip().startswith('| Skill Name'):
            # table rows start at i+2
            for row in lines[i+2:]:
                if not row.strip().startswith('|'):
                    break
                parts = [p.strip() for p in row.split('|')]
                if len(parts) >= 4:
                    src = parts[3]
                    # if src looks like a path, keep it
                    if src and not src.startswith('http'):
                        sources.add(str((ROOT / src).resolve()))
            break
    return sorted(sources)


def make_report(missing_agents, orphan_agents, missing_skills, orphan_skills, out_path):
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open('w', encoding='utf-8') as f:
        f.write('# Consistency Report\n\n')
        f.write('Generated by scripts/check_summaries_consistency.py\n\n')

        f.write('## Agents missing from summaries/agent_en.md\n\n')
        if missing_agents:
            for a in missing_agents:
                f.write(f'- {a}\n')
        else:
            f.write('- None\n')

        f.write('\n## Agent summary entries referencing missing agent files\n\n')
        if orphan_agents:
            for a in orphan_agents:
                f.write(f'- {a}\n')
        else:
            f.write('- None\n')

        f.write('\n## Skills missing from summaries/skill_en.md\n\n')
        if missing_skills:
            for s in missing_skills:
                f.write(f'- {s}\n')
        else:
            f.write('- None\n')

        f.write('\n## Skill summary table rows referencing missing SKILL.md\n\n')
        if orphan_skills:
            for s in orphan_skills:
                f.write(f'- {s}\n')
        else:
            f.write('- None\n')

    return p


def main():
    agent_files = find_agent_files()
    agent_summary_md = ROOT / 'summaries' / 'agent_en.md'
    agent_summary_paths = parse_agent_summary_paths(agent_summary_md)

    agent_files_set = set([str(Path(p).resolve()) for p in agent_files])
    agent_summary_set = set([str(Path(p).resolve()) for p in agent_summary_paths])

    missing_agents = sorted([p for p in agent_files_set if p not in agent_summary_set])
    orphan_agents = sorted([p for p in agent_summary_set if p not in agent_files_set])

    skill_files = find_skill_files()
    skill_summary_md = ROOT / 'summaries' / 'skill_en.md'
    skill_summary_sources = parse_skill_table_sources(skill_summary_md)

    skill_files_set = set([str(Path(p).resolve()) for p in skill_files])
    skill_summary_set = set([str(Path(p).resolve()) for p in skill_summary_sources])

    missing_skills = sorted([p for p in skill_files_set if p not in skill_summary_set])
    orphan_skills = sorted([p for p in skill_summary_set if p not in skill_files_set])

    report = make_report(missing_agents, orphan_agents, missing_skills, orphan_skills, ROOT / 'reports' / 'consistency_report.md')
    print(f'Report written to {report}')


if __name__ == '__main__':
    main()
